# Generated by Django 4.2.2 on 2023-06-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("1", "Masculin"), ("2", "Féminin")], max_length=8
                    ),
                ),
                ("firstname", models.CharField(max_length=25)),
                ("birthyear", models.CharField(max_length=4)),
            ],
        ),
    ]
