# Generated by Django 4.2.2 on 2023-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insee_names", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="name",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
